# REF: https://nodered.org/docs/getting-started/docker#docker-stack--docker-compose

version: "3.7"

services:

  # REF: https://hub.docker.com/r/oitc/modbus-server
  modbus-server:
    container_name: modbus-server
    image: oitc/modbus-server
    command: -f /server_config.json
    ports:
      - 5020:5020
    volumes:
      - ./server.json:/server_config.json:ro

  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Madrid
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - node-red-data:/data
    depends_on:
      - modbus-server

volumes:
  node-red-data:

networks:
  node-red-net:
